- name: Testowy playbook lokalny
  hosts: local
  tasks:
    - name: Stwórz plik w /tmp/
      copy:
        content: "Druga wersja pliku\n"
        dest: /tmp/ansible-test.txt

- name: Drugi job
  hosts: local
  tasks:
    - name: Task pierwszy
      copy:
        content: "Drugi job???\n"
        dest: /tmp/mp-drugi.txt

- name: Trzeci job
  hosts: local
  tasks:
    - name: Task trzeci
      copy:
        content: "Trzeci chyba już job???\n"
        dest: /tmp/mp-trzeci.txt
